### PR TITLE
2.x updates

### PR DESCRIPTION
**Pull request by dissolve**
only part i'm not sure on is the tests as i was switching off the the microformats/tests suite

### CODE REVIEW

**Comment by jeena** [comment]
Perhaps this happened somewhere else but I persorally would like to have some process in place for contribution where at least one other person reviews the code from a pull request before it is committed to the master branch.

**Comment by dissolve** [comment]
Probably best to review the conversation here. 
https://chat.indieweb.org/microformats/2017-05-05#t1494009290491000

**Comment by jeena** [comment]
Thanks for the link

**Comment by veganstraightedge** [comment]
But I agree. There should be some community review of changes and that review should happen here on GitHub. Moving forward, let's do that.

**Comment by dissolve** [comment]
As there is some clean-up to do, deprecation warnings to add, and I want to revert the test set changes.  Would it make sense to revert these changes and push them to a new branch to allow better review?

**Pull request merged**
